name: Publish

concurrency: production

# This action should process only on push to 'production' branch
on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "liberica"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
#         TODO Uncomment this field if you want to build only your project
#      - name: Build with Gradle
#        run: ./gradlew clean build
#         TODO Uncomment this field if you want to build and publish your project
#      - name: Build and Publish with Gradle
#        run: ./gradlew clean build publishToMyNexus
#        env: # TODO Configure you own github-secrets
#          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
#          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}